#!/usr/bin/env node
// Build pipeline for lily-design-system-vue-headless.
//
//   1. Generate `index.ts` — the public barrel re-exporting every SFC in
//      `components/`. Generated, not hand-maintained: the catalog is ~491
//      components and grows, and an omitted entry is invisible to
//      consumers even though the file ships in the tarball.
//   2. Bundle to `dist/index.mjs` with Vite library mode (SFCs need the
//      Vue compiler, so tsup/esbuild alone will not do).
//   3. Emit `.d.ts` alongside it with vue-tsc.
//
// Why this exists: until 0.3.0 the package declared `"main": "index.js"`
// and no such file was ever built, so importing the package failed at
// resolution for every consumer.
//
// vue-tsc must stay on 2.x while TypeScript is 5.x — vue-tsc 3.x resolves
// `typescript/lib/tsc`, a subpath TypeScript 7 no longer exports.

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const componentsDir = path.join(root, "components");

const files = fs
  .readdirSync(componentsDir)
  .filter((name) => name.endsWith(".vue"))
  .sort();

if (files.length === 0) {
  throw new Error(`No .vue components found in ${componentsDir}.`);
}

const seen = new Set();
const lines = [];
for (const file of files) {
  const name = file.slice(0, -".vue".length);
  if (seen.has(name)) {
    throw new Error(`Duplicate component export "${name}".`);
  }
  seen.add(name);
  lines.push(`export { default as ${name} } from "./components/${name}.vue";`);
}

fs.writeFileSync(
  path.join(root, "index.ts"),
  "// Generated by build.mjs — do not edit by hand.\n" +
    "// Barrel export of every component in the Lily Design System catalog.\n\n" +
    lines.join("\n") +
    "\n",
);
console.log(`generated index.ts (${files.length} components)`);

// Clean first: vite runs with `emptyOutDir: false` (vue-tsc writes into
// the same dist afterwards and must not be wiped by the second step), so
// without this a renamed or removed component leaves its stale .d.ts
// behind and the barrel keeps type-resolving against a file that no
// longer has a source.
fs.rmSync(path.join(root, "dist"), { recursive: true, force: true });

const run = (cmd, args) =>
  execFileSync(cmd, args, { cwd: root, stdio: "inherit" });

run("npx", ["vite", "build", "--config", "vite.lib.config.ts"]);
run("npx", ["vue-tsc", "-p", "tsconfig.lib.json", "--emitDeclarationOnly"]);

// `files` ships only `dist/`, so an empty bundle would publish a package
// that installs and exports nothing.
for (const artifact of ["index.mjs", "index.d.ts"]) {
  const file = path.join(root, "dist", artifact);
  if (!fs.existsSync(file) || fs.statSync(file).size === 0) {
    throw new Error(`expected a non-empty dist/${artifact} after build.`);
  }
}
console.log("build ok");
